"use client";
import { useEffect, useMemo, useState } from "react";
import { ArrowUpRight, BarChart3, Bot, Check, ChevronDown, Cpu, Database, ExternalLink, Filter, Github, HardDrive, Search, Sparkles, Terminal, X, Zap } from "lucide-react";
import { models } from "../lib/models";
import { rankModels, scoreForHardware } from "../lib/scoring";
import { AIModel } from "../lib/types";

const categories = ["All models", "LLM", "Coding", "Image generation", "Video generation", "STT", "Music generation", "OCR / Document AI", "Segmentation", "Depth / Geometry", "3D generation"];
const filters = ["Open Source", "Commercial use", "Local only", "Apple Silicon", "Quantized"];
type Platform = "mac" | "windows" | "linux";
const fileName = (model: AIModel) => model.downloadFile ?? ({
  "qwen3-8": "Qwen3.8-27B-Q4_K_M.gguf",
  "qwen-coder": "Qwen3-Coder-Next-Q4_K_M.gguf",
  "qwen-image": "Qwen-Image-8bit.safetensors",
  "ideogram-4": "ideogram-4-nf4.safetensors",
  "ace-step": "ace-step-1.5-xl-turbo.safetensors",
  "qwen-asr": "Qwen3-ASR-1.7B",
  "glm-ocr": "GLM-OCR-0.9B",
  "sam-31": "sam3.1_hiera_large.pt",
  "depth-3": "depth_anything_v3.safetensors",
  "trellis-2": "TRELLIS.2-4B-int8.safetensors",
  "glm-53": "GLM-5.3-BF16.safetensors"
}[model.id] ?? `${model.name.replace(/\s+/g, "-")}-${model.formats[0].toLowerCase()}.safetensors`);
const appName = (model: AIModel) => model.installTarget ?? model.apps[0];
const formatFor = (model: AIModel, platform: Platform) => platform === "mac" && model.formats.includes("MLX") ? "MLX" : model.formats.includes("GGUF") ? "GGUF" : model.formats[0];
const formatUrl = (model: AIModel, platform: Platform) => platform === "mac" && model.mlxUrl ? model.mlxUrl : model.ggufUrl ?? model.repoUrl ?? `https://huggingface.co/models?search=${encodeURIComponent(model.name)}`;

function FitBadge({ score }: { score: number }) { const color = score >= 70 ? "good" : score >= 45 ? "warn" : "bad"; const label = score >= 90 ? "Excellent" : score >= 70 ? "Recommended" : score >= 45 ? "Optimization" : "Cloud recommended"; return <span className={`fit ${color}`}><i /> {label}</span>; }
function ModelCard({ model, mode, platform, selected, onSelect, onGuide }: { model: AIModel; mode: "global" | "local"; platform: Platform; selected: boolean; onSelect: () => void; onGuide: () => void }) {
  const score = scoreForHardware(model, 64); const primaryApp = appName(model); return <article className={`model-card ${selected ? "selected" : ""}`}>
    <div className="card-top"><div className="rank">{model.frontier ? "FRONTIER" : mode === "local" ? `#${Math.max(1, rankModels(models.filter(x => x.category === model.category), "local").indexOf(model) + 1)}` : "TOP PICK"}</div><button className={`checkbox ${selected ? "checked" : ""}`} onClick={onSelect}>{selected && <Check size={14} />}</button></div>
    <div className="model-title"><div className="model-icon"><Bot size={21} /></div><div><h3>{model.name}</h3><p>{model.org} <span>·</span> {model.updated}</p></div><a className="repo-link" href={model.repoUrl ?? `https://huggingface.co/models?search=${encodeURIComponent(model.name)}`} target="_blank" rel="noreferrer" aria-label={`${model.name} Hugging Face 모델 페이지 열기`}><ExternalLink size={14} /></a></div>
    <p className="desc">{model.description}</p><div className="tags">{model.tags.map(t => <span key={t}>{t}</span>)}</div>
    <div className="metric-grid"><div><small>PARAMETERS</small><strong>{model.params}</strong></div><div><small>MEMORY</small><strong>{model.memory}</strong></div><div><small>LICENSE</small><strong className={model.commercial === true ? "lime" : "amber"}>{model.license}</strong></div></div>
    <div className="fit-row"><FitBadge score={mode === "local" ? score : model.fit} /><span className="score">{mode === "local" ? score : model.fit}<small>/100 fit</small></span></div>
    <div className="apps"><span>실행 앱</span>{model.apps.slice(0, 3).map(a => <b key={a}>{a}</b>)}</div><div className="filename"><span>{platform === "mac" ? "Mac 권장" : `${platform} 권장`}</span><a href={formatUrl(model, platform)} target="_blank" rel="noreferrer" title="Hugging Face에서 파일 확인"><code>{fileName(model)}</code></a></div>
    <div className="verify-line"><Check size={12} /> {primaryApp} 실행 경로 · {model.confidence} 신뢰도</div>
    <button className="guide-btn" onClick={onGuide}>사용법과 근거 보기 <ArrowUpRight size={15} /></button>
  </article>
}

export default function Home() {
  const [mode, setMode] = useState<"global" | "local">("local"); const [category, setCategory] = useState("All models"); const [query, setQuery] = useState(""); const [activeFilters, setActiveFilters] = useState<string[]>([]); const [selected, setSelected] = useState<string[]>([]); const [guide, setGuide] = useState<AIModel | null>(models[0]); const [live, setLive] = useState(false); const [platform, setPlatform] = useState<Platform>("mac");
  useEffect(() => { const ua = navigator.userAgent.toLowerCase(); setPlatform(ua.includes("mac") ? "mac" : ua.includes("win") ? "windows" : "linux"); }, []);
  const visible = useMemo(() => { let list = rankModels(models, mode); if (category !== "All models") list = list.filter(m => m.category === category); if (query) list = list.filter(m => `${m.name} ${m.org} ${m.tags.join(" ")}`.toLowerCase().includes(query.toLowerCase())); if (activeFilters.includes("Open Source")) list = list.filter(m => m.license === "Open Source"); if (activeFilters.includes("Commercial use")) list = list.filter(m => m.commercial === true); if (activeFilters.includes("Local only")) list = list.filter(m => !m.frontier); if (activeFilters.includes("Quantized")) list = list.filter(m => m.formats.some(f => /Q|INT|NF|8-bit/i.test(f))); return list; }, [mode, category, query, activeFilters]);
  const toggleFilter = (f: string) => setActiveFilters(v => v.includes(f) ? v.filter(x => x !== f) : [...v, f]); const toggleSelected = (id: string) => setSelected(v => v.includes(id) ? v.filter(x => x !== id) : [...v, id]);
  const compareModels = models.filter(m => selected.includes(m.id));
  return <main>
    <section className="hero"><div><div className="eyebrow"><span className="live-dot" /> 최신 AI INDEX <span className="divider" /> 업데이트 {live ? "실시간 확인 중" : "2026.09.14"}</div><h1>가장 좋은 AI를 찾고<br /><span>내 컴퓨터에서 실행하세요.</span></h1><p className="hero-copy">지금 공개된 모델을 탐색하고, 내 컴퓨터에서 실제로 실행 가능한지 확인해보세요.</p><div className="hero-actions"><button className="primary" onClick={() => document.getElementById("finder")?.scrollIntoView({ behavior: "smooth" })}>모델 탐색하기 <ArrowUpRight size={16} /></button><button className="ghost" onClick={() => setLive(!live)}><Zap size={15} /> {live ? "실시간 확인 중" : "작동 방식"}</button></div></div><div className="hardware-card"><div className="hardware-head"><span><Cpu size={16} /> 감지된 하드웨어</span><span className="green-label">● 사용 가능</span></div><h2>Apple M2 Max</h2><div className="hardware-specs"><div><small>메모리</small><b>64 GB</b></div><div><small>GPU</small><b>38-core</b></div><div><small>가속 백엔드</small><b>Metal / MPS</b></div></div><div className="memory-bar"><span /><i>64 GB 통합 메모리</i></div><div className="hardware-note">OS에 맞는 다운로드 형식을 우선 제안합니다. GPU·메모리는 브라우저 제한상 프로필 확인이 필요합니다.</div><label className="platform-select">실행 OS<select value={platform} onChange={e => setPlatform(e.target.value as Platform)}><option value="mac">macOS · MLX 우선</option><option value="windows">Windows · GGUF 우선</option><option value="linux">Linux · GGUF 우선</option></select></label></div></section>
    <section className="index-strip"><div><span className="strip-icon"><Database size={17} /></span><div><b>1,284</b><small>색인된 모델</small></div></div><div><span className="strip-icon"><BarChart3 size={17} /></span><div><b>42</b><small>추적 카테고리</small></div></div><div><span className="strip-icon"><HardDrive size={17} /></span><div><b>LOCAL-FIRST</b><small>하드웨어 매칭</small></div></div><div className="strip-note">Hugging Face Hub 데이터 기반 <ExternalLink size={13} /></div></section>
    <section className="finder" id="finder"><div className="section-heading"><div><div className="eyebrow">01 / 탐색</div><h2>무엇을 만들고 있나요?</h2><p>기능별로 살펴보고, 실제 실행 가능성을 비교하세요.</p></div><div className="view-switch"><button className={mode === "global" ? "active" : ""} onClick={() => setMode("global")}>전체 성능 기준</button><button className={mode === "local" ? "active" : ""} onClick={() => setMode("local")}>내 Mac 기준 <span>✦</span></button></div></div>
      <div className="notice"><Check size={14} /> 현재 결과는 seed catalog 기반입니다. `실시간 검색`을 켜면 Hugging Face 최신 정보 확인 단계로 표시됩니다.</div><div className="toolbar"><div className="searchbox"><Search size={18} /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="모델명, 기능, 작업 검색..." /><kbd>⌘ K</kbd></div><button className={`live-toggle ${live ? "on" : ""}`} onClick={() => setLive(!live)}><span /> {live ? "실시간 검색 켜짐" : "빠른 검색"}</button></div>
      <div className="category-row scrollbar">{categories.map(c => <button key={c} className={category === c ? "active" : ""} onClick={() => setCategory(c)}>{c}{c === "All models" && <span>{models.length}</span>}</button>)}</div><div className="filter-row"><Filter size={15} /><span>필터</span>{filters.map(f => <button key={f} className={activeFilters.includes(f) ? "active" : ""} onClick={() => toggleFilter(f)}>{activeFilters.includes(f) && <Check size={13} />}{f === "Open Source" ? "오픈소스" : f === "Commercial use" ? "상업 이용" : f === "Local only" ? "로컬 실행" : f === "Apple Silicon" ? "Apple Silicon" : "Quantized"}</button>)}<span className="result-count">{visible.length}개 결과 <ChevronDown size={14} /></span></div>
      <div className="results-meta"><span><b>{mode === "local" ? "내 컴퓨터에서 실행 가능한 모델" : "전체 성능이 높은 모델"}</b>을 표시합니다</span><span className="sort">정렬: <b>카테고리 적합성 · {mode === "local" ? "하드웨어 적합성" : "성능"}</b> <ChevronDown size={14} /></span></div><div className="cards-grid">{visible.map(m => <ModelCard key={m.id} model={m} mode={mode} platform={platform} selected={selected.includes(m.id)} onSelect={() => toggleSelected(m.id)} onGuide={() => setGuide(m)} />)}</div></section>
    <section className="bottom-section"><div className="ask-card"><div className="eyebrow">✦ AI에게 질문</div><h2>정확한 추천이 필요하신가요?</h2><p>목표와 입력 파일을 알려주면 설치 순서와 결과 전달 방법을 더 정확하게 정리할 수 있습니다.</p><div className="question-chips"><button>목표: 결과물 생성</button><button>실행: GUI 앱</button><button>입력: 텍스트·이미지</button></div><div className="ask-input"><input placeholder="예: M2 Max에서 이미지와 OCR을 연결하고 싶어요" /><button aria-label="질문 보내기"><ArrowUpRight size={17} /></button></div><div className="prompts"><button>한국어 STT 추천 <ArrowUpRight size={12} /></button><button>Qwen3-ASR과 Whisper 비교 <ArrowUpRight size={12} /></button></div></div><div className="guide-card"><div className="guide-label"><Terminal size={15} /> 빠른 시작 가이드</div><h3>{guide?.name ?? "모델을 선택하세요"}</h3><p>현재 하드웨어 기준 추천 실행 경로입니다.</p><div className="guide-step"><span>01</span><div><b>{guide ? fileName(guide) : "정확한 파일명"} 다운로드</b><small>먼저 {guide ? appName(guide) : "추천 앱"}을 설치하고 앱 안에서 검색하세요.</small></div><Check size={16} /></div><div className="guide-step"><span>02</span><div><b>{guide ? appName(guide) : "실행 앱"}에서 열기</b><small>{guide?.apps[0] === "LM Studio" ? "LM Studio 실행 → 모델명 검색 → 파일 크기 확인 → Download → Load" : "애플리케이션 설치 → 모델 파일 등록 → 실행 → 결과 저장"}</small></div><ArrowUpRight size={15} /></div><div className="evidence"><b>검증 상태</b><span><Check size={12} /> {live ? "Live Search 확인 대기" : "Seed catalog 기록 · 다운로드 전 확인 필요"}</span><span><Check size={12} /> Model card: {guide?.confidence ?? "-"} confidence</span><span><Check size={12} /> Hardware fit: {guide ? scoreForHardware(guide, 64) : "-"}/100</span></div><button className="full-guide">전체 설치 안내 보기 <ArrowUpRight size={15} /></button></div></section>
    {selected.length > 0 && <div className="compare-bar"><span><b>{selected.length}</b>개 모델 선택됨</span><button onClick={() => setSelected([])}>선택 해제</button><button className="primary" onClick={() => setGuide(compareModels[0] ?? null)}>비교 결과 보기 <ArrowUpRight size={15} /></button></div>}
    {selected.length > 1 && <section className="compare-panel"><div className="compare-title"><div><div className="eyebrow">02 / 실행 설계</div><h2>선택한 AI로 만드는 실무 파이프라인</h2><p>앞 단계의 결과를 다음 모델 입력으로 연결하는 순서입니다.</p></div><button aria-label="선택 해제" onClick={() => setSelected([])}><X size={18} /></button></div><div className="pipeline">{compareModels.map((m, i) => <div className="pipeline-step" key={m.id}><div className="pipeline-number">{String(i + 1).padStart(2, "0")}</div><div className="pipeline-body"><div className="pipeline-heading"><b>{appName(m)} 설치</b><span>{m.category}</span></div><p>{i === 0 ? "먼저 앱을 설치하고 모델을 준비합니다." : `이전 단계의 ${compareModels[i - 1].name} 결과를 입력으로 사용합니다.`}</p><div className="pipeline-actions"><code>{fileName(m)}</code><span>↓</span><b>{m.name} 실행</b><span>↓</span><em>{m.outputHint ?? "결과 파일 저장"}</em></div></div></div>)}</div><div className="pipeline-result"><Sparkles size={16} /><div><b>최종 제안</b><span>{compareModels.map(m => m.name).join(" → ")} 순서로 설치·다운로드·실행한 뒤, 각 결과를 다음 모델에 첨부하면 목적에 맞는 결과를 만들 수 있습니다.</span></div></div></section>}
    <footer><div className="brand"><span className="brand-mark">✳</span><span>OPEN AI <em>FINDER</em></span></div><span>실제로 실행할 수 있는 공개 AI를 찾습니다.</span><div>Hugging Face Hub <Github size={15} /></div></footer>
  </main>;
}
