"use client";
import { useMemo, useState } from "react";
import { ArrowUpRight, BarChart3, Bot, Check, ChevronDown, Cpu, Database, ExternalLink, Filter, Github, HardDrive, Menu, Search, Settings2, Terminal, X, Zap } from "lucide-react";
import { models } from "../lib/models";
import { rankModels, scoreForHardware } from "../lib/scoring";
import { AIModel } from "../lib/types";

const categories = ["All models", "LLM", "Coding", "Image generation", "Video generation", "STT", "Music generation", "OCR / Document AI", "Segmentation", "Depth / Geometry", "3D generation"];
const filters = ["Open Source", "Commercial use", "Local only", "Apple Silicon", "Quantized"];

function FitBadge({ score }: { score: number }) { const color = score >= 70 ? "good" : score >= 45 ? "warn" : "bad"; const label = score >= 90 ? "Excellent" : score >= 70 ? "Recommended" : score >= 45 ? "Optimization" : "Cloud recommended"; return <span className={`fit ${color}`}><i /> {label}</span>; }
function ModelCard({ model, mode, selected, onSelect, onGuide }: { model: AIModel; mode: "global" | "local"; selected: boolean; onSelect: () => void; onGuide: () => void }) {
  const score = scoreForHardware(model, 64); const primaryApp = model.apps[0]; return <article className={`model-card ${selected ? "selected" : ""}`}>
    <div className="card-top"><div className="rank">{model.frontier ? "FRONTIER" : mode === "local" ? `#${Math.max(1, rankModels(models.filter(x => x.category === model.category), "local").indexOf(model) + 1)}` : "TOP PICK"}</div><button className={`checkbox ${selected ? "checked" : ""}`} onClick={onSelect}>{selected && <Check size={14} />}</button></div>
    <div className="model-title"><div className="model-icon"><Bot size={21} /></div><div><h3>{model.name}</h3><p>{model.org} <span>·</span> {model.updated}</p></div></div>
    <p className="desc">{model.description}</p><div className="tags">{model.tags.map(t => <span key={t}>{t}</span>)}</div>
    <div className="metric-grid"><div><small>PARAMETERS</small><strong>{model.params}</strong></div><div><small>MEMORY</small><strong>{model.memory}</strong></div><div><small>LICENSE</small><strong className={model.commercial === true ? "lime" : "amber"}>{model.license}</strong></div></div>
    <div className="fit-row"><FitBadge score={mode === "local" ? score : model.fit} /><span className="score">{mode === "local" ? score : model.fit}<small>/100 fit</small></span></div>
    <div className="apps"><span>실행 앱</span>{model.apps.slice(0, 3).map(a => <b key={a}>{a}</b>)}</div>
    <div className="verify-line"><Check size={12} /> {primaryApp} 실행 경로 · {model.confidence} 신뢰도</div>
    <button className="guide-btn" onClick={onGuide}>사용법과 근거 보기 <ArrowUpRight size={15} /></button>
  </article>
}

export default function Home() {
  const [mode, setMode] = useState<"global" | "local">("local"); const [category, setCategory] = useState("All models"); const [query, setQuery] = useState(""); const [activeFilters, setActiveFilters] = useState<string[]>([]); const [selected, setSelected] = useState<string[]>([]); const [guide, setGuide] = useState<AIModel | null>(models[0]); const [live, setLive] = useState(false);
  const visible = useMemo(() => { let list = rankModels(models, mode); if (category !== "All models") list = list.filter(m => m.category === category); if (query) list = list.filter(m => `${m.name} ${m.org} ${m.tags.join(" ")}`.toLowerCase().includes(query.toLowerCase())); if (activeFilters.includes("Open Source")) list = list.filter(m => m.license === "Open Source"); if (activeFilters.includes("Commercial use")) list = list.filter(m => m.commercial === true); if (activeFilters.includes("Local only")) list = list.filter(m => !m.frontier); if (activeFilters.includes("Quantized")) list = list.filter(m => m.formats.some(f => /Q|INT|NF|8-bit/i.test(f))); return list; }, [mode, category, query, activeFilters]);
  const toggleFilter = (f: string) => setActiveFilters(v => v.includes(f) ? v.filter(x => x !== f) : [...v, f]); const toggleSelected = (id: string) => setSelected(v => v.includes(id) ? v.filter(x => x !== id) : [...v, id]);
  const compareModels = models.filter(m => selected.includes(m.id));
  return <main><nav className="nav"><div className="brand"><span className="brand-mark">✳</span><span>OPEN AI <em>FINDER</em></span></div><div className="nav-links"><a className="active">탐색</a><a>모델 비교 <sup>BETA</sup></a><a>하드웨어</a><a>소개</a></div><div className="nav-actions"><span className="status-dot" /> <span>INDEX ONLINE</span><button className="icon-btn"><Settings2 size={17} /></button><div className="avatar">IY</div></div><button className="mobile-menu"><Menu size={20} /></button></nav>
    <section className="hero"><div><div className="eyebrow"><span className="live-dot" /> 최신 AI INDEX <span className="divider" /> 업데이트 {live ? "실시간 확인 중" : "2026.09.14"}</div><h1>가장 좋은 AI를 찾고<br /><span>내 컴퓨터에서 실행하세요.</span></h1><p className="hero-copy">지금 공개된 모델을 탐색하고, 내 컴퓨터에서 실제로 실행 가능한지 확인해보세요.</p><div className="hero-actions"><button className="primary" onClick={() => document.getElementById("finder")?.scrollIntoView({ behavior: "smooth" })}>모델 탐색하기 <ArrowUpRight size={16} /></button><button className="ghost" onClick={() => setLive(!live)}><Zap size={15} /> {live ? "실시간 확인 중" : "작동 방식"}</button></div></div><div className="hardware-card"><div className="hardware-head"><span><Cpu size={16} /> 감지된 하드웨어</span><span className="green-label">● 사용 가능</span></div><h2>Apple M2 Max</h2><div className="hardware-specs"><div><small>메모리</small><b>64 GB</b></div><div><small>GPU</small><b>38-core</b></div><div><small>가속 백엔드</small><b>Metal / MPS</b></div></div><div className="memory-bar"><span /><i>64 GB 통합 메모리</i></div><button className="hardware-link">하드웨어 상세 보기 <ChevronDown size={14} /></button></div></section>
    <section className="index-strip"><div><span className="strip-icon"><Database size={17} /></span><div><b>1,284</b><small>색인된 모델</small></div></div><div><span className="strip-icon"><BarChart3 size={17} /></span><div><b>42</b><small>추적 카테고리</small></div></div><div><span className="strip-icon"><HardDrive size={17} /></span><div><b>LOCAL-FIRST</b><small>하드웨어 매칭</small></div></div><div className="strip-note">Hugging Face Hub 데이터 기반 <ExternalLink size={13} /></div></section>
    <section className="finder" id="finder"><div className="section-heading"><div><div className="eyebrow">01 / 탐색</div><h2>무엇을 만들고 있나요?</h2><p>기능별로 살펴보고, 실제 실행 가능성을 비교하세요.</p></div><div className="view-switch"><button className={mode === "global" ? "active" : ""} onClick={() => setMode("global")}>전체 성능 기준</button><button className={mode === "local" ? "active" : ""} onClick={() => setMode("local")}>내 Mac 기준 <span>✦</span></button></div></div>
      <div className="notice"><Check size={14} /> 현재 결과는 seed catalog 기반입니다. `실시간 검색`을 켜면 Hugging Face 최신 정보 확인 단계로 표시됩니다.</div><div className="toolbar"><div className="searchbox"><Search size={18} /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="모델명, 기능, 작업 검색..." /><kbd>⌘ K</kbd></div><button className={`live-toggle ${live ? "on" : ""}`} onClick={() => setLive(!live)}><span /> {live ? "실시간 검색 켜짐" : "빠른 검색"}</button></div>
      <div className="category-row scrollbar">{categories.map(c => <button key={c} className={category === c ? "active" : ""} onClick={() => setCategory(c)}>{c}{c === "All models" && <span>{models.length}</span>}</button>)}</div><div className="filter-row"><Filter size={15} /><span>필터</span>{filters.map(f => <button key={f} className={activeFilters.includes(f) ? "active" : ""} onClick={() => toggleFilter(f)}>{activeFilters.includes(f) && <Check size={13} />}{f === "Open Source" ? "오픈소스" : f === "Commercial use" ? "상업 이용" : f === "Local only" ? "로컬 실행" : f === "Apple Silicon" ? "Apple Silicon" : "Quantized"}</button>)}<span className="result-count">{visible.length}개 결과 <ChevronDown size={14} /></span></div>
      <div className="results-meta"><span><b>{mode === "local" ? "내 컴퓨터에서 실행 가능한 모델" : "전체 성능이 높은 모델"}</b>을 표시합니다</span><span className="sort">정렬: <b>{mode === "local" ? "하드웨어 적합성" : "성능"}</b> <ChevronDown size={14} /></span></div><div className="cards-grid">{visible.map(m => <ModelCard key={m.id} model={m} mode={mode} selected={selected.includes(m.id)} onSelect={() => toggleSelected(m.id)} onGuide={() => setGuide(m)} />)}</div></section>
    <section className="bottom-section"><div className="ask-card"><div className="eyebrow">✦ AI에게 질문</div><h2>어디서 시작할지 모르겠나요?</h2><p>모델, 하드웨어, 작업에 맞는 실행 방법을 질문해보세요.</p><div className="ask-input"><input placeholder="예: M2 Max에 가장 좋은 이미지 모델은?" /><button><ArrowUpRight size={17} /></button></div><div className="prompts"><button>한국어 STT 추천 <ArrowUpRight size={12} /></button><button>Qwen3-ASR과 Whisper 비교 <ArrowUpRight size={12} /></button></div></div><div className="guide-card"><div className="guide-label"><Terminal size={15} /> 빠른 시작 가이드</div><h3>{guide?.name ?? "모델을 선택하세요"}</h3><p>현재 하드웨어 기준 추천 실행 경로입니다.</p><div className="guide-step"><span>01</span><div><b>{guide?.formats[0] ?? "호환 버전"} 다운로드</b><small>64 GB 통합 메모리 기준 추천 형식</small></div><Check size={16} /></div><div className="guide-step"><span>02</span><div><b>{guide?.apps[0] ?? "실행 앱"}에서 열기</b><small>{guide?.apps[0] === "LM Studio" ? "초보자에게 가장 쉬운 로컬 GUI" : "이 모델의 공식 실행 경로와 호환되는 앱"}</small></div><ArrowUpRight size={15} /></div><div className="evidence"><b>검증 상태</b><span><Check size={12} /> {live ? "Live Search 확인 대기" : "Seed catalog 기록"}</span><span><Check size={12} /> Model card: {guide?.confidence ?? "-"} confidence</span><span><Check size={12} /> Hardware fit: {guide ? scoreForHardware(guide, 64) : "-"}/100</span></div><button className="full-guide">전체 설치 안내 보기 <ArrowUpRight size={15} /></button></div></section>
    {selected.length > 0 && <div className="compare-bar"><span><b>{selected.length}</b>개 모델 선택됨</span><button onClick={() => setSelected([])}>선택 해제</button><button className="primary" onClick={() => setGuide(compareModels[0] ?? null)}>비교 결과 보기 <ArrowUpRight size={15} /></button></div>}
    {selected.length > 1 && <section className="compare-panel"><div className="compare-title"><div><div className="eyebrow">02 / 비교</div><h2>선택한 모델을 나란히 비교합니다</h2></div><button onClick={() => setSelected([])}><X size={18} /></button></div><div className="compare-table">{compareModels.map(m => <div className="compare-col" key={m.id}><b>{m.name}</b><span>{m.category}</span><strong>{scoreForHardware(m, 64)}/100</strong><small>하드웨어 적합성</small><span>{m.memory}</span><span>{m.license}</span><span>{m.apps[0]}</span></div>)}</div></section>}
    <footer><div className="brand"><span className="brand-mark">✳</span><span>OPEN AI <em>FINDER</em></span></div><span>실제로 실행할 수 있는 공개 AI를 찾습니다.</span><div>Hugging Face Hub <Github size={15} /></div></footer>
  </main>;
}
