import { AIModel } from "./types";
export const models: AIModel[] = [
  { id: "qwen3-8", name: "Qwen3.8-27B", org: "Qwen", category: "LLM", tags: ["Reasoning", "Coding", "Vision"], description: "A capable multimodal generalist for local chat, coding, and agents.", params: "27B", memory: "18–28 GB+", fit: 96, license: "Open Source", commercial: true, formats: ["Q4_K_M", "MLX", "BF16"], apps: ["LM Studio", "Ollama", "MLX", "Transformers"], updated: "Sep 2026", benchmark: "SWE-bench Pro 61.7", confidence: "High" },
  { id: "qwen-coder", name: "Qwen3-Coder-Next", org: "Qwen", category: "Coding", tags: ["256K Context", "Agent", "Tool calling"], description: "Coding-agent optimized model for repo-scale work and tool use.", params: "80B / 3B active", memory: "20–48 GB+", fit: 84, license: "Open Source", commercial: true, formats: ["Q4", "GGUF"], apps: ["Ollama", "LM Studio", "vLLM"], updated: "Aug 2026", benchmark: "Repo-scale coding", confidence: "High" },
  { id: "qwen-image", name: "Qwen-Image", org: "Qwen", category: "Image generation", tags: ["Text to image", "Editing", "Apache 2.0"], description: "Versatile image generation and editing with a strong Apple Silicon story.", params: "20B", memory: "16 GB (8-bit)", fit: 92, license: "Open Source", commercial: true, formats: ["8-bit", "FP16"], apps: ["ComfyUI", "Draw Things", "Transformers"], updated: "Aug 2026", benchmark: "Image edit / typography", confidence: "High" },
  { id: "ideogram-4", name: "Ideogram 4", org: "Ideogram", category: "Image generation", tags: ["Typography", "Open weights", "NF4"], description: "High-quality image generation with exceptional text rendering.", params: "9.3B", memory: "16–24 GB", fit: 88, license: "Non-Commercial", commercial: false, formats: ["NF4", "FP8"], apps: ["ComfyUI", "Draw Things"], updated: "Jun 2026", benchmark: "Typography quality", confidence: "Medium" },
  { id: "ace-step", name: "ACE-Step 1.5 XL", org: "ACE Studio", category: "Music generation", tags: ["Audio", "Turbo", "12 GB GPU"], description: "A practical local music generator with an 8-step Turbo path.", params: "4B DiT", memory: "12–24 GB VRAM", fit: 76, license: "Open Weights", commercial: "conditional", formats: ["INT8", "FP16"], apps: ["ComfyUI", "Transformers"], updated: "Sep 2026", benchmark: "12 GB with offload", confidence: "High" },
  { id: "qwen-asr", name: "Qwen3-ASR 1.7B", org: "Qwen", category: "STT", tags: ["Multilingual", "Auto detect", "Korean"], description: "Fast multilingual speech recognition with a lightweight 0.6B sibling.", params: "1.7B", memory: "4–8 GB", fit: 98, license: "Open Source", commercial: true, formats: ["BF16", "INT8"], apps: ["Transformers", "MLX"], updated: "Sep 2026", benchmark: "Multilingual ASR", confidence: "High" },
  { id: "glm-ocr", name: "GLM-OCR", org: "Z.ai", category: "OCR / Document AI", tags: ["Tables", "Formula", "0.9B"], description: "A compact document reader for layouts, tables, formulas, and extraction.", params: "0.9B", memory: "4–8 GB", fit: 97, license: "Open Source", commercial: true, formats: ["BF16", "INT8"], apps: ["Ollama", "Transformers", "vLLM"], updated: "Sep 2026", benchmark: "OmniDocBench 94.62", confidence: "High" },
  { id: "sam-31", name: "SAM 3.1", org: "Meta", category: "Segmentation", tags: ["Video", "Text concept", "Interactive"], description: "Interactive image and video segmentation for complex subjects.", params: "Vision", memory: "8–16 GB", fit: 90, license: "Open Source", commercial: "conditional", formats: ["FP16"], apps: ["ComfyUI", "Transformers"], updated: "Aug 2026", benchmark: "Mask + tracking", confidence: "High" },
  { id: "depth-3", name: "Depth Anything 3", org: "Depth Anything", category: "Depth / Geometry", tags: ["Camera pose", "3D", "AR"], description: "Depth, multi-view geometry, and camera pose for VFX and 3D workflows.", params: "Vision", memory: "8–16 GB", fit: 89, license: "Open Source", commercial: true, formats: ["FP16"], apps: ["ComfyUI", "Transformers"], updated: "Sep 2026", benchmark: "Metric depth", confidence: "High" },
  { id: "trellis-2", name: "TRELLIS.2-4B", org: "Microsoft", category: "3D generation", tags: ["Image to 3D", "INT8", "ComfyUI"], description: "A focused image-to-3D model with practical quantized workflows.", params: "4B", memory: "12–24 GB", fit: 78, license: "Open Weights", commercial: "conditional", formats: ["INT8", "FP16"], apps: ["ComfyUI", "Transformers"], updated: "Jul 2026", benchmark: "Mesh quality", confidence: "Medium" },
  { id: "glm-53", name: "GLM-5.3", org: "Z.ai", category: "Coding", tags: ["Frontier", "Cloud", "756 GB"], description: "Frontier-scale comparison candidate; not a practical personal-computer download.", params: "Large", memory: "756 GB storage", fit: 22, license: "Restricted", commercial: "conditional", formats: ["BF16"], apps: ["vLLM", "SGLang"], updated: "Sep 2026", benchmark: "Frontier benchmark", frontier: true, confidence: "Medium" }
];
