import { AIModel } from "./types";
export const models: AIModel[] = [
  { id: "qwen3-8", name: "Qwen3.8-27B", org: "Qwen", category: "LLM", tags: ["Reasoning", "Coding", "Vision"], description: "A capable multimodal generalist for local chat, coding, and agents.", params: "27B", memory: "18–28 GB+", fit: 96, license: "Open Source", commercial: true, formats: ["Q4_K_M", "MLX", "BF16"], apps: ["LM Studio", "Ollama", "MLX", "Transformers"], updated: "Sep 2026", benchmark: "SWE-bench Pro 61.7", confidence: "High" },
  { id: "qwen-coder", name: "Qwen3-Coder-Next", org: "Qwen", category: "Coding", tags: ["256K Context", "Agent", "Tool calling"], description: "Coding-agent optimized model for repo-scale work and tool use.", params: "80B / 3B active", memory: "20–48 GB+", fit: 84, license: "Open Source", commercial: true, formats: ["Q4", "GGUF"], apps: ["Ollama", "LM Studio", "vLLM"], updated: "Aug 2026", benchmark: "Repo-scale coding", confidence: "High" },
  { id: "qwen-image", name: "Qwen-Image", org: "Qwen", category: "Image generation", tags: ["Text to image", "Editing", "Apache 2.0"], description: "Versatile image generation and editing with a strong Apple Silicon story.", params: "20B", memory: "16 GB (8-bit)", fit: 92, license: "Open Source", commercial: true, formats: ["8-bit", "FP16"], apps: ["ComfyUI", "Draw Things", "Transformers"], updated: "Aug 2026", benchmark: "Image edit / typography", confidence: "High" },
  { id: "ideogram-4", name: "Ideogram 4", org: "Ideogram", category: "Image generation", tags: ["Typography", "Open weights", "NF4"], description: "High-quality image generation with exceptional text rendering.", params: "9.3B", memory: "16–24 GB", fit: 88, license: "Non-Commercial", commercial: false, formats: ["NF4", "FP8"], apps: ["ComfyUI", "Draw Things"], updated: "Jun 2026", benchmark: "Typography quality", confidence: "Medium" },
  { id: "ace-step", name: "ACE-Step 1.5 XL", org: "ACE Studio", category: "Music generation", tags: ["Audio", "Turbo", "12 GB GPU"], description: "A practical local music generator with an 8-step Turbo path.", params: "4B DiT", memory: "12–24 GB VRAM", fit: 76, license: "Open Weights", commercial: "conditional", formats: ["INT8", "FP16"], apps: ["ComfyUI", "Transformers"], updated: "Sep 2026", benchmark: "12 GB with offload", confidence: "High" },
  { id: "qwen-asr", name: "Qwen3-ASR 1.7B", org: "Qwen", category: "STT", tags: ["Multilingual", "Auto detect", "Korean"], description: "Fast multilingual speech recognition with a lightweight 0.6B sibling.", params: "1.7B", memory: "4–8 GB", fit: 98, license: "Open Source", commercial: true, formats: ["BF16", "INT8"], apps: ["Transformers", "MLX"], updated: "Sep 2026", benchmark: "Multilingual ASR", confidence: "High" },
  { id: "glm-ocr", name: "GLM-OCR", org: "Z.ai", category: "OCR / Document AI", tags: ["Tables", "Formula", "0.9B"], description: "A compact document reader for layouts, tables, formulas, and extraction.", params: "0.9B", memory: "4–8 GB", fit: 97, license: "Open Source", commercial: true, formats: ["BF16", "INT8"], apps: ["Ollama", "Transformers", "vLLM"], updated: "Sep 2026", benchmark: "OmniDocBench 94.62", confidence: "High" },
  { id: "sam-31", name: "SAM 3.1", org: "Meta", category: "Segmentation", tags: ["Video", "Text concept", "Interactive"], description: "Interactive image and video segmentation for complex subjects.", params: "Vision", memory: "8–16 GB", fit: 90, license: "Open Source", commercial: "conditional", formats: ["FP16"], apps: ["ComfyUI", "Transformers"], updated: "Aug 2026", benchmark: "Mask + tracking", confidence: "High" },
  { id: "depth-3", name: "Depth Anything 3", org: "Depth Anything", category: "Depth / Geometry", tags: ["Camera pose", "3D", "AR"], description: "Depth, multi-view geometry, and camera pose for VFX and 3D workflows.", params: "Vision", memory: "8–16 GB", fit: 89, license: "Open Source", commercial: true, formats: ["FP16"], apps: ["ComfyUI", "Transformers"], updated: "Sep 2026", benchmark: "Metric depth", confidence: "High" },
  { id: "trellis-2", name: "TRELLIS.2-4B", org: "Microsoft", category: "3D generation", tags: ["Image to 3D", "INT8", "ComfyUI"], description: "A focused image-to-3D model with practical quantized workflows.", params: "4B", memory: "12–24 GB", fit: 78, license: "Open Weights", commercial: "conditional", formats: ["INT8", "FP16"], apps: ["ComfyUI", "Transformers"], updated: "Jul 2026", benchmark: "Mesh quality", confidence: "Medium" },
  { id: "glm-53", name: "GLM-5.3", org: "Z.ai", category: "Coding", tags: ["Frontier", "Cloud", "756 GB"], description: "Frontier-scale comparison candidate; not a practical personal-computer download.", params: "Large", memory: "756 GB storage", fit: 22, license: "Restricted", commercial: "conditional", formats: ["BF16"], apps: ["vLLM", "SGLang"], updated: "Sep 2026", benchmark: "Frontier benchmark", frontier: true, confidence: "Medium" },
  { id: "minicpm5", name: "MiniCPM5-2B", org: "openbmb", category: "LLM", tags: ["3B", "Lightweight", "GGUF"], description: "Compact general model with official GGUF and MLX community variants.", params: "3B", memory: "4–8 GB", fit: 95, license: "Open Source", commercial: true, formats: ["GGUF", "MLX"], apps: ["LM Studio", "Ollama", "MLX"], updated: "Sep 2026", benchmark: "Community adoption", confidence: "High", repoUrl: "https://huggingface.co/openbmb/MiniCPM5-2B", ggufUrl: "https://huggingface.co/openbmb/MiniCPM5-2B-GGUF", mlxUrl: "https://huggingface.co/openbmb/MiniCPM5-2B-MLX", downloadFile: "MiniCPM5-2B-Q4_K_M.gguf", installTarget: "LM Studio", outputHint: "대화 결과를 Markdown으로 저장" },
  { id: "gpt-oss-20b", name: "gpt-oss-20b", org: "OpenAI", category: "Reasoning", tags: ["Reasoning", "Open weights", "Tool use"], description: "Open-weight reasoning model for local inference and tool workflows.", params: "21B", memory: "16–24 GB", fit: 88, license: "Open Source", commercial: true, formats: ["MXFP4", "GGUF"], apps: ["Ollama", "LM Studio", "Transformers"], updated: "Aug 2026", benchmark: "Reasoning", confidence: "High", repoUrl: "https://huggingface.co/openai/gpt-oss-20b", ggufUrl: "https://huggingface.co/models?search=gpt-oss-20b%20GGUF", downloadFile: "gpt-oss-20b-MXFP4.gguf", installTarget: "Ollama", outputHint: "추론 답변과 tool call 로그를 JSON으로 저장" },
  { id: "qwen-coder-30b", name: "Qwen3-Coder-30B-A3B-Instruct", org: "Qwen", category: "Coding", tags: ["3B active", "Agent", "GGUF"], description: "A proven coding-agent baseline with a much more practical local footprint.", params: "31B / 3B active", memory: "18–28 GB", fit: 91, license: "Open Source", commercial: true, formats: ["GGUF", "MLX"], apps: ["Ollama", "LM Studio", "MLX"], updated: "Dec 2025", benchmark: "Coding agent", confidence: "High", repoUrl: "https://huggingface.co/Qwen/Qwen3-Coder-30B-A3B-Instruct", ggufUrl: "https://huggingface.co/models?search=Qwen3-Coder-30B-A3B-GGUF", mlxUrl: "https://huggingface.co/models?search=Qwen3-Coder-30B-A3B-MLX", downloadFile: "Qwen3-Coder-30B-A3B-Instruct-Q4_K_M.gguf", installTarget: "Ollama", outputHint: "코드 diff와 테스트 로그를 저장" },
  { id: "ltx-25", name: "LTX-2.5", org: "Lightricks", category: "Video generation", tags: ["Video + audio", "Multishot", "ComfyUI"], description: "Open-weight video and audio generation designed for self-hosted workflows.", params: "Diffusion", memory: "24 GB+ VRAM", fit: 46, license: "Open Weights", commercial: "conditional", formats: ["Diffusion"], apps: ["ComfyUI", "Transformers"], updated: "Sep 2026", benchmark: "Video + audio", confidence: "High", repoUrl: "https://huggingface.co/Lightricks/LTX-2.5", downloadFile: "LTX-2.5-dev.safetensors", installTarget: "ComfyUI", outputHint: "MP4와 WAV를 함께 저장해 편집 타임라인으로 전달" },
  { id: "minimax-h3", name: "MiniMax-H3", org: "MiniMaxAI", category: "Video generation", tags: ["2K", "Audio", "I2V"], description: "Omni-modal video model with synchronized audio; cloud or high-memory GPU recommended.", params: "33B", memory: "48 GB+ VRAM", fit: 30, license: "Restricted", commercial: "conditional", formats: ["BF16", "GGUF"], apps: ["ComfyUI", "Transformers"], updated: "Sep 2026", benchmark: "Video + audio", frontier: true, confidence: "High", repoUrl: "https://huggingface.co/MiniMaxAI/MiniMax-H3", ggufUrl: "https://huggingface.co/unsloth/MiniMax-H3-GGUF", downloadFile: "MiniMax-H3-Base.safetensors", installTarget: "ComfyUI", outputHint: "영상·오디오 결과를 MP4로 검수" },
  { id: "vibevoice-asr", name: "VibeVoice-ASR-Streaming-7B", org: "microsoft", category: "STT", tags: ["Streaming", "ASR", "Multilingual"], description: "Streaming speech recognition candidate for long-form audio.", params: "7B", memory: "12–16 GB", fit: 82, license: "Open Source", commercial: true, formats: ["BF16", "INT8"], apps: ["Transformers", "MLX"], updated: "Sep 2026", benchmark: "Streaming ASR", confidence: "Medium", repoUrl: "https://huggingface.co/microsoft/VibeVoice-ASR-Streaming-7B", downloadFile: "VibeVoice-ASR-Streaming-7B", installTarget: "Transformers", outputHint: "SRT와 타임스탬프 JSON을 저장" },
  { id: "minilm", name: "all-MiniLM-L6-v2", org: "sentence-transformers", category: "Embedding", tags: ["22M", "RAG", "Similarity"], description: "Small, widely adopted embedding baseline for local search and RAG.", params: "22M", memory: "1–2 GB", fit: 99, license: "Open Source", commercial: true, formats: ["PyTorch", "ONNX"], apps: ["Transformers"], updated: "Jun 2023", benchmark: "Sentence similarity", confidence: "High", repoUrl: "https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2", downloadFile: "all-MiniLM-L6-v2", installTarget: "Transformers", outputHint: "벡터 인덱스와 검색 결과를 저장" },
  { id: "yue2", name: "YuE2-3B", org: "m-a-p", category: "Music generation", tags: ["Text to audio", "3B", "Open"], description: "A compact open music generation candidate for local experiments.", params: "3B", memory: "12–16 GB", fit: 73, license: "Open Weights", commercial: "conditional", formats: ["BF16", "INT8"], apps: ["Transformers", "ComfyUI"], updated: "Sep 2026", benchmark: "Music generation", confidence: "Medium", repoUrl: "https://huggingface.co/m-a-p/YuE2-3B", downloadFile: "YuE2-3B.safetensors", installTarget: "Transformers", outputHint: "WAV stems와 prompt metadata를 저장" },
  { id: "granite-42-8b", name: "granite-4.2-8b", org: "IBM", category: "LLM", tags: ["Enterprise", "8B", "Instruction"], description: "An enterprise-oriented open model that fits a broad local hardware range.", params: "9B", memory: "8–12 GB", fit: 86, license: "Open Source", commercial: true, formats: ["BF16", "GGUF"], apps: ["Ollama", "LM Studio", "Transformers"], updated: "Sep 2026", benchmark: "Instruction following", confidence: "High", repoUrl: "https://huggingface.co/ibm-granite/granite-4.2-8b", downloadFile: "granite-4.2-8b-Q4_K_M.gguf", installTarget: "Ollama", outputHint: "구조화된 JSON 결과를 저장" }
];
